static/css/identify.css, templates/users/identify.html
#28 
- 登入頁面-選擇身份（使用者或公司方）
- 目前只有畫面切版(html css)，之後加入路徑後會用jinja2語法改寫
=> 登入頁面-選擇身份（使用者或公司方）切版

companies/forms.py, companies/models.py
增加資料驗證功能
- 電子郵件是否已被註冊
- 公司名稱是否符合格式
- 統一編號應為 8 位數字
- 姓名格式是否符合格式
- 電話號碼格式是否符合格式
=> 增加公司會員系統驗證資料功能

poetry.lock
=> 檢查lock檔，檢查圖片上傳功能 

templates/base.html, users/urls.py
1.如title, 新增path, 測試過程如下!!!!:
https://github.com/astrocamp/16th-EngiLink/assets/111471602/77e7ca3e-1353-417f-b211-8c371abbe767
=> 新增使用者與履歷一對多關聯

.gitignore, css/output.css, poetry.lock, pyproject.toml, resumes/models.py, templates/base.html, templates/resumes/area.html
1. 加入css/output.css進忽略檔
2. 將resume的profile檔案, 最大尺寸設為300x300後在存入s3, 等比例縮放
=> 上傳圖片裁切大小統一

core/settings.py, poetry.lock, pyproject.toml, static/output.css, users/views.py
剛剛閱讀文件，mailgun需要購買一個domain才可以脫離測試功能（目前mailgun只能用預設的沙盒，都要手動添加驗證過的mail，吃不進表單自填的資訊）所以我目前先用smtp做註冊成功的信件。
後續如果討論有要花錢買domain再說！感謝
=> user註冊成功信（smtp)

css/output.css, templates/resumes/create.html, templates/resumes/index.html, templates/resumes/total.html
resumes/index.html、create.html和total.html 改成tailwind 
後續文字細節會再微調，先大概打好底
=> resumes/index.html、create.html和total.html 改成tailwind 

.gitignore, README.md, poetry.lock, pyproject.toml, resumes/urls.py, resumes/views.py, templates/pdf_template.html, templates/resumes/total.html
https://youtu.be/QbjsIZi6hvY
測試時記得下載套件!!!
=> 一鍵下載履歷 PDF

.gitignore, css/output.css, jobs/forms.py, jobs/views.py, templates/jobs/index.html, templates/jobs/job.html, templates/jobs/show.html
在package.json，有安裝HTMX的套件
刊登中、已下架狀態的轉換，不會整個頁面跳轉，只會有狀態字的改變。
https://github.com/astrocamp/16th-EngiLink/assets/144601116/d2db2af4-a533-4311-ab07-45e0650eee85
=> 刊登職缺的狀態(HTMX改寫) 

templates/educations/create.html, templates/educations/index.html, templates/educations/update.html, templates/projects/create.html, templates/projects/index.html, templates/projects/update.html, templates/resumes/create.html, templates/resumes/index.html, templates/resumes/total.html, templates/resumes/update.html, templates/shared/navbar.html, templates/works/create.html, templates/works/index.html, templates/works/update.html
=> 履歷、教育、專案、工作css改成tailwind 

companies/urls.py, companies/views.py, templates/home.html
#155 
註冊公司會員後，直接到填寫公司所需欄位的頁面
首頁的求職者按鈕和公司會員按鈕，按進去後，直接到登入頁面
[測試影片](https://youtu.be/nVC540APahY)
=> 判斷user是否為公司會員，修正路徑

companies/views.py
CompanyDetailView是DetailView，不需要再用form_class(因為DetailView沒有處理到表單，只用來顯示單個用戶資訊）。
拿掉後不影響
=> 修正companies.views中的混用 

templates/users/login.html, templates/users/register.html
=> 求職者登入、註冊畫面

templates/companies/login.html, templates/companies/register.html
=> 公司登入和註冊畫面切版

templates/users/login.html
=> 更正求職者登入頁面文字

companies/views.py, templates/companies/list.html
=> 找公司 頁面補上搜尋公司

static/js/drag.js, static/js/entry.js, templates/resumes/total2.html
1. 修正頁面如果有ul-> li都可以拖放問題
2. 用alpine綁x-data, 避免所有頁面都能拖放問題, 導致按鈕不能點擊.
3. 目前navbar已經可以點選
=> 熱修: 修正drag.js會在其他頁面造成拖放問題

templates/jobs/create.html, templates/jobs/edit.html, templates/jobs/show.html
將公司編輯職缺頁面進行切版，小螢幕（手機）也不會跑版
網頁：
手機：
網頁：
手機：
網頁：
手機：
錄影測試：(超過10MB，用連結方式）
https://youtu.be/jOQzmG04pmc
=> 公司編輯職缺頁面切版

templates/companies/update.html
#253
#222 
新增的公司欄位，之後合進去dev，再開票處理
=> 公司udpate.html的切版

companies/views.py
#238
如果公司帳號沒有完成填寫公司資料
則會跳回update的頁面
https://github.com/astrocamp/16th-EngiLink/assets/144601116/674975fb-4f8a-4bbc-81fd-0f2ea1be1e35
=> 新增公司登入頁面的判斷

static/js/entry.js, templates/resumes/total5.html, templates/shared/collect_btn.html, templates/users/home.html, templates/users/jobs.html, users/views.py
1. 使用者登入時, 推薦職缺頁面, home.html有迴圈包迴圈, 導致如果有多間公司時, 收藏某職缺, 會造成其他公司的對應到id的職缺也自動被收藏.
2. htmx切換收藏按鈕, 畫面不跳轉.
3. navbar的找工作連結暫時未連, 使用者未登入時, 收藏按鈕功能取消.
https://github.com/astrocamp/16th-EngiLink/assets/111471602/2fe12928-16d8-4ab2-a11c-7e5c512a38fb
=> 修復搜尋公司頁面迴圈問題

templates/jobs/list.html, templates/shared/navbar.html, templates/users/home.html
修正使用者推薦工作頁面
修復navbar 找工作裡面立即應徵 我的收藏缺少的路徑
=> 修復navbar缺少的路徑和修正使用者推薦工作頁面

templates/jobs/job.html
=> hotfix:刊登職缺路徑

templates/companies/update.html
因為在 #222 有新增欄位，所以在update.html新增input
今天練簡報的時候，發現公司和求職者顏色一樣，會搞不清楚現在到底在哪裡(如果我是台下觀眾的話)
所以剛把它改了顏色
顏色可以再討論，我是隨便選的，選一個反差比較大的
https://github.com/astrocamp/16th-EngiLink/assets/144601116/437d77dd-6a42-486e-ba4a-34cd2f6969d1
=> 新增公司update.html的切版

templates/companies/detail.html
=> 公司detail.html資料切版

templates/users/detail.html
=> 使用者detail.html資料切版

templates/companies/login.html, templates/companies/register.html, templates/users/register.html, users/views.py
#283 
公司、求職者的註冊頁面加入placeholder
修改公司的顏色，我先統一改紫色，可修改
https://github.com/astrocamp/16th-EngiLink/assets/144601116/f036be86-cd23-4c58-a631-35ef19e4a6fb
=> 註冊頁面加入placeholder

templates/backend.html
補回js/bundle.js，讓navbar的資料選單能夠點選收攏
=> 熱修backend.html

templates/users/update.html
=> 使用者update.html切版

static/js/htmx.js, templates/shared/collect_btn.html, templates/users/home.html, users/views.py
=> hotfix: 修正users/home.html問題

companies/views.py, templates/companies/update.html
#299 
沒有出現None了!!!
原本存在的資料也還在!!!不影響
=> 修復公司註冊頁面的空白欄位出現None

templates/resumes/area.html
=> 創建履歷按鈕顯示修正

templates/jobs/apply.html, templates/resumes/update.html
1. 刪除履歷功能修復完成
2. 現在沒有履歷, 想投職缺會顯示創建履歷按鈕
=> 修復履歷刪除, 沒有履歷投遞職缺錯誤問題

resumes/forms.py
=> hotfix: resumes/forms.py type error

templates/resumes/area.html
=> 拿掉履歷表單登出按鈕

users/views.py
#349 
https://github.com/astrocamp/16th-EngiLink/assets/144601116/f19b5acc-56dc-47ff-911c-d22937769bf1
=> 修正求職者註冊成功，直接到home頁面

templates/companies/login.html, users/forms.py
=> 使用者與公司登入的帳號改成用戶名

jobs/views.py, templates/jobs/edit.html
#337 
原本是跳回職缺的id，修正完，跳回原本公司的id
測試影片
https://github.com/astrocamp/16th-EngiLink/assets/144601116/a78900ee-a5d5-4c5b-a895-546af7f8d177
=> 修正職缺頁面編輯完成後，跳回原本的公司id

resumes/forms.py, templates/educations/create.html, templates/educations/update.html, templates/projects/create.html, templates/projects/update.html, templates/resumes/create.html, templates/resumes/update.html, templates/works/create.html, templates/works/update.html
=> 增加表單alter到所有履歷頁面

templates/shared/navbar.html
1. 噴錯原因, 公司尚未註冊成功, 故不會有user.company.id
=> hotfix:公司註冊完噴錯

companies/forms.py, templates/companies/login.html, templates/users/create.html
#368 
需要註冊公司，才會跳到這個頁面
測試這頁，可以先把navbar關掉再測試，以免噴錯（問題已修復，合進dev了）
加了紅色*為必填，其他未加*，改為非必填
新增電話驗證，會跳出輸入正確格式
移除None
=> 修改公司註冊後的詳細資訊欄位

templates/companies/home.html, templates/shared/navbar.html
原先：
https://github.com/astrocamp/16th-EngiLink/assets/157874138/a4aa70fa-8d84-4598-9f0f-1304cdbc1deb
解決後可正常使用
=> 漢堡選單和navbar上刊登職缺路徑沒反應

static/js/font.js, templates/companies/list.html, templates/users/home.html
把求職者的推薦公司比讚的icon改回來，並利用軒佑安裝好的套件改成i標籤
也把找公司的icon改用 i 標籤（原為google font)
(示範畫面會不一樣，是因為在不同的螢幕截圖）
推薦公司（原本）：
推薦公司更改後：
找公司更改前：
找公司更改後：
=> 修改推薦公司、找公司icon

jobs/views.py, templates/jobs/list.html, templates/shared/collect_btn.html, templates/users/home.html
=> fix: 收藏icon

templates/companies/home.html, templates/shared/navbar.html
=> 修正公司方漢堡表單選項 

static/js/font.js, templates/companies/info.html
- 點選公司地址旁邊的icon連結，可以外連到google地圖，顯示公司位置，讓使用者可查詢公司位置跟交通路線
- 順便把失連的工作類型icon補回去
測試錄影：
https://github.com/astrocamp/16th-EngiLink/assets/149367532/0242bdd7-823e-411a-b1fc-1b18aaa20cdc
=> 公司地址連結google地圖

educations/rules.py, educations/views.py, projects/rules.py, projects/views.py, resumes/apps.py, resumes/rules.py, resumes/views.py, templates/educations/update.html, templates/projects/update.html, templates/works/update.html, users/rules.py, works/rules.py, works/views.py
#294 
https://github.com/astrocamp/16th-EngiLink/assets/144601116/f07d7a7b-b4de-4763-be64-df0142bf7e62
以下路徑
- resumes
path("<pk>/"),
path("edit/<pk>/"),
path("delete/<pk>/"),
path("total/<pk>/"),
- educations、works、projects
path("<pk>/edit/"),
path("<pk>/delete/),
path("<pk>/education/"),
path("<pk>/educations/"),
path("<pk>/work/"),
path("<pk>/works/"),
path("<pk>/project/"),
path("<pk>/projects/"),
=> resumes educations projects works 權限設定

core/urls.py, core/views.py
避免出現，明明有登入，但又有登入按鈕的bug
https://github.com/astrocamp/16th-EngiLink/assets/157874138/fd41acc0-36c3-4f7a-a086-6c7d16b0c07d
https://github.com/astrocamp/16th-EngiLink/assets/157874138/5269b030-571f-4265-9537-441cf2b2776b
=> 登入後不能再返回首頁

templates/companies/update.html, templates/jobs/create.html, templates/jobs/edit.html, templates/jobs/job.html, templates/jobs/show.html, templates/resumes/create.html, templates/resumes/update.html
=> 人數需求、工作經驗、薪資沒有寫單位 & 提示圖片上傳格式

core/settings.py, educations/models.py, projects/models.py, static/js/drag.js, templates/resumes/total.html, works/models.py
style1~style3履歷皆可拖拉.
https://github.com/astrocamp/16th-EngiLink/assets/111471602/dc49768f-84ed-4d0f-be65-bd7c938d4824
=> fix:履歷模板拖放功能

resumes/views.py
=> hotfix:創建履歷權限

static/js/font.js, templates/companies/login.html, templates/users/login.html
因使用google官方按鈕無法導入跳轉功能，故改用一般按鈕形式，添加Font Awesome 的G圖示
=> Google登入按鈕

templates/companies/home.html, templates/jobs/index.html, templates/users/calendar.html
=> 公司首頁切版和移除職缺列表多餘按鈕

templates/resumes/index.html
=> 熱修: 應該是有人解衝突誤蓋

jobs/views.py, templates/companies/list.html, templates/jobs/list.html, templates/users/home.html
=> 修改找公司搜尋 bar 樣式及增加找工作的搜尋 bar

companies/views.py, resumes/views.py, templates/resumes/style1.html, templates/resumes/style2.html, templates/resumes/style3.html, templates/shared/navbar.html
#513 
https://github.com/astrocamp/16th-EngiLink/assets/144601116/3db3576b-d0be-47f7-95ce-b1be5c7490e8
=> 面試查看履歷的樣式呈現

resumes/forms.py
#500 
https://github.com/astrocamp/16th-EngiLink/assets/144601116/62a9db5a-aecf-45ae-af67-9951111e33e0
=> 修正resume非必填欄位，沒填寫不會噴錯

templates/educations/index.html, templates/projects/index.html, templates/works/index.html
=> 修改教育、工作、專案的按鈕樣式

templates/shared/navbar.html
=> 修改公司navbar顏色樣式

companies/views.py, templates/companies/home.html
=> 公司首頁的照片為預設 未帶入公司上傳的圖片

.gitignore, core/settings.py, static/js/alpine.js, static/js/drag.js, static/js/sweetalert.js, templates/resumes/create.html, templates/resumes/update.html, templates/users/create.html, users/views.py
npm run dev or npm run build~~
1. 使用者建立履歷, 更新履歷時
2. 公司新增資料頁面時
https://github.com/astrocamp/16th-EngiLink/assets/111471602/c06ee525-7eac-4824-8241-aa587361f5f6
=> 表單送出之後 loading 畫面「處理中...」

companies/views.py, templates/companies/info.html
=> 路徑info.html收藏職缺功能修改

templates/companies/home.html
=> 公司首頁 RWD 圖片跑版

templates/resumes/index.html
=> 手機履歷navbar連結跑版 

templates/projects/index.html
=> 手機履歷專案欄位清單跑版

templates/jobs/apply.html
=> 手機選擇履歷連結跑版

companies/views.py, resumes/views.py, templates/companies/list.html, templates/resumes/base_template.html, templates/resumes/style1.html, templates/resumes/style2.html, templates/resumes/style3.html, templates/resumes/update_style.html
#555 #561
修改公司查看履歷的navbar顏色
修改選擇樣式的頁面，移除藍色背景
修改找公司的照片，logo改成圓形，讓它是滿版。
修改後，原本的total.html不會被影響
修改找公司的照片，logo改成圓形，讓它是滿版。
=> 修改公司查看履歷的navbar顏色

companies/views.py, templates/companies/list.html
#574 
未登入時，找公司頁面的img滑上去時，擋住navbar
點選公司詳細資訊時跳錯誤訊息
https://github.com/astrocamp/16th-EngiLink/assets/144601116/3dd3982a-2865-410f-8052-cee680a6819b
=> 未登入時，找公司頁面的問題

companies/views.py, templates/shared/collect_btn.html, templates/shared/collect_company.html, templates/shared/collect_company1.html, templates/users/collect_companies.html, templates/users/home.html, users/views.py
https://github.com/astrocamp/16th-EngiLink/assets/111471602/03c477aa-30d4-49f7-9c8a-baf4658db839
=> 修正收藏公司跳轉問題

templates/jobs/apply.html
=> 未建立履歷投遞職缺會噴錯 

companies/views.py, templates/companies/list.html
=> 未登入點擊收藏會跳轉到third party畫面

templates/users/apply.html, templates/users/calendar.html
=> 提交履歷紀錄下面的框框有點看不出來是提交進度，可以給個標示說這是投遞履歷的進度 

educations/forms.py, works/forms.py
=> 入學時間、工作經驗畢業時間可以做個驗證，畢業時間不能比入學時間早

about/views.py
=> 修正LINE Pay跳轉路徑

users/views.py
=> 使用者更改密碼的頁面壞 

companies/views.py, jobs/views.py, templates/companies/filter_company.html, templates/companies/list.html, templates/jobs/filter_job.html, templates/jobs/list.html, templates/users/home.html, templates/users/jobs_and_companies.html, users/views.py
#562 
用HTMX改寫，把渲染的部分重新拉出來
https://github.com/astrocamp/16th-EngiLink/assets/144601116/0eb28127-428a-4176-86c2-9a2be3264768
=> 修正公司、工作、首頁的搜尋跳轉

core/settings.py, templates/404.html, templates/500.html
=> 新增：404, 500頁面

templates/jobs/list.html
=> 找工作頁面卡片連結沒包好，圖片點擊無法進到 show 頁面（找公司的有包好可參考）

companies/urls.py, companies/views.py, templates/shared/collect_company1.html, templates/users/collect_companies.html
https://github.com/astrocamp/16th-EngiLink/assets/111471602/574ae23c-e6f9-4154-b160-6d0bc174da3a
=> hotfix: 收藏公司頁面, company.id對不上問題

companies/views.py, templates/companies/filter_company.html
=> 修復：收藏公司頁面無法刪除問題 

templates/jobs/apply.html
=> 應徵時沒選履歷會壞掉

templates/companies/apply.html
=> 固定應徵紀錄卡片高度 

templates/resumes/style3.html
=> 修正style3.html RWD

templates/jobs/filter_job.html
=> 修改filter_job.html跑版問題
